name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  sshd-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/yeniklas/pvcmount-sshd:latest
            ghcr.io/yeniklas/pvcmount-sshd:${{ github.ref_name }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build \
            -ldflags "-X main.version=${{ github.ref_name }}" \
            -o pvcmount-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }} \
            .

      - uses: actions/upload-artifact@v4
        with:
          name: pvcmount-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: pvcmount-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: [sshd-image, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: 'pvcmount-*'

      - uses: softprops/action-gh-release@v2
        with:
          files: 'pvcmount-*'
